
services:
  db:
    image: postgres:9.5
    container_name: pgDocker9-5
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=root
     - POSTGRES_DB=LojaVirtualApplication
	 - POSTGRES_MAX_CONNECTIONS=200
    volumes:
      - postgreVolume:/var/lib/postgres
      - ./init:/docker-entrypoint-initdb.d
    restart:
      always
    ports:
      - "5449:5432"
    
volumes:
  postgreVolume: